# Generated by Django 4.2.10 on 2024-02-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0002_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module_code',
            field=models.CharField(default='CM3035', max_length=256),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='CM3035', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
