# Generated by Django 4.2.10 on 2024-02-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0004_userprofile_status_alter_course_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
