# Generated by Django 4.2.10 on 2024-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0005_assignment_startdate_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses_enrolled', to='elearn_app.userprofile'),
        ),
    ]
