# Generated by Django 4.2.10 on 2024-03-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn_app', '0008_feedback_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
